# Evidence Collection Script for Criterion #5 Latency Verification
# Phase 1 Gate: p95 < 10ms
#
# Usage: .\collect_evidence.ps1
# Prerequisites: Benchmarks must have been run (cargo bench)

param(
    [switch]$SkipBenchmarks = $false,
    [double]$TargetP95Ms = 10.0
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
$EvidenceDir = $PSScriptRoot
$CriterionDir = Join-Path $ProjectRoot "target\criterion"
$CargoExe = "C:\Users\nokho\.cargo\bin\cargo.exe"

Write-Host "="*70 -ForegroundColor Cyan
Write-Host "Phase 1 Criterion #5 Evidence Collection" -ForegroundColor Cyan
Write-Host "Target: p95 < $TargetP95Ms ms" -ForegroundColor Cyan
Write-Host "="*70 -ForegroundColor Cyan
Write-Host ""

# Step 1: Run benchmarks (unless skipped)
if (-not $SkipBenchmarks) {
    Write-Host "[1/5] Running component latency benchmarks..." -ForegroundColor Yellow
    Set-Location $ProjectRoot
    & $CargoExe bench --bench websocket_latency

    if ($LASTEXITCODE -ne 0) {
        Write-Error "Benchmark execution failed with exit code $LASTEXITCODE"
    }

    Write-Host "✅ Benchmarks complete`n" -ForegroundColor Green
} else {
    Write-Host "[1/5] Skipping benchmark execution (using existing results)`n" -ForegroundColor Gray
}

# Step 2: Check Criterion output exists
Write-Host "[2/5] Validating Criterion output..." -ForegroundColor Yellow

if (-not (Test-Path $CriterionDir)) {
    Write-Error "Criterion output directory not found: $CriterionDir"
}

$EstimatesFiles = Get-ChildItem -Path $CriterionDir -Recurse -Filter "estimates.json"
Write-Host "Found $($EstimatesFiles.Count) benchmark result(s)" -ForegroundColor Gray

if ($EstimatesFiles.Count -eq 0) {
    Write-Error "No benchmark results found. Run benchmarks first."
}

Write-Host "✅ Criterion output validated`n" -ForegroundColor Green

# Step 3: Extract metrics using Python script
Write-Host "[3/5] Extracting latency metrics..." -ForegroundColor Yellow

$ExtractScript = Join-Path $EvidenceDir "extract_metrics.py"
& python $ExtractScript

if ($LASTEXITCODE -ne 0) {
    Write-Warning "Metric extraction reported issues (exit code: $LASTEXITCODE)"
} else {
    Write-Host "✅ Metrics extracted`n" -ForegroundColor Green
}

# Step 4: Copy Criterion HTML reports
Write-Host "[4/5] Copying Criterion HTML reports..." -ForegroundColor Yellow

$HtmlReportDir = Join-Path $EvidenceDir "criterion_reports"
if (Test-Path $HtmlReportDir) {
    Remove-Item $HtmlReportDir -Recurse -Force
}
New-Item -ItemType Directory -Path $HtmlReportDir -Force | Out-Null

# Copy all Criterion HTML reports
Get-ChildItem -Path $CriterionDir -Directory | ForEach-Object {
    $ReportHtml = Join-Path $_.FullName "report\index.html"
    if (Test-Path $ReportHtml) {
        $DestDir = Join-Path $HtmlReportDir $_.Name
        Copy-Item -Path (Join-Path $_.FullName "report") -Destination $DestDir -Recurse -Force
        Write-Host "  Copied: $($_.Name)" -ForegroundColor Gray
    }
}

Write-Host "✅ HTML reports copied to: $HtmlReportDir`n" -ForegroundColor Green

# Step 5: Generate final summary
Write-Host "[5/5] Generating final summary..." -ForegroundColor Yellow

$SummaryFile = Join-Path $EvidenceDir "EVIDENCE_SUMMARY.md"
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$SummaryContent = @"
# Phase 1 Criterion #5 Evidence Summary

**Date:** $Timestamp
**Owner:** performance-engineer
**Target:** p95 < $TargetP95Ms ms (Phase 1 gate)

## Evidence Collected

### 1. Benchmark Results
- **Report:** [benchmark_results.md](./benchmark_results.md)
- **Criterion HTML:** [criterion_reports/](./criterion_reports/)

### 2. Raw Data
- **Location:** ``target/criterion/``
- **Format:** Criterion.rs JSON + CSV

### 3. Verification Status
- **Plan Reference:** Phase 1 Verification Plan §3.5
- **SRS Reference:** §7.1 (Phase 1 acceptance), §5.1.2 (latency targets)

## How to Review

1. **Quick Check:** Read [benchmark_results.md](./benchmark_results.md) for pass/fail verdict
2. **Detailed Analysis:** Open Criterion HTML reports in browser
3. **Raw Data:** Analyze CSV files in ``target/criterion/*/new/raw.csv``

## Reproduction

``````powershell
# Re-run benchmarks
cargo bench --bench websocket_latency

# Re-generate evidence
.\collect_evidence.ps1 -SkipBenchmarks
``````

## Next Steps

- [ ] Review results with qa-lead
- [ ] If PASS: Update Phase 1 gate tracker
- [ ] If FAIL: Root cause analysis + optimization plan

---

**Generated by:** collect_evidence.ps1
**Project:** MONOTERMINAL Phase 1
"@

$SummaryContent | Out-File -FilePath $SummaryFile -Encoding UTF8
Write-Host "✅ Summary written to: $SummaryFile`n" -ForegroundColor Green

# Final verdict
Write-Host "="*70 -ForegroundColor Cyan
Write-Host "Evidence Collection Complete" -ForegroundColor Cyan
Write-Host "="*70 -ForegroundColor Cyan
Write-Host ""
Write-Host "📁 Evidence Directory: $EvidenceDir" -ForegroundColor White
Write-Host "📊 Results:            $EvidenceDir\benchmark_results.md" -ForegroundColor White
Write-Host "📈 HTML Reports:       $EvidenceDir\criterion_reports\" -ForegroundColor White
Write-Host ""

# Display benchmark results if available
$ResultsFile = Join-Path $EvidenceDir "benchmark_results.md"
if (Test-Path $ResultsFile) {
    Write-Host "Latest Results:" -ForegroundColor Yellow
    Write-Host ""
    Get-Content $ResultsFile | Select-Object -First 20
    Write-Host ""
    Write-Host "... (see full report in benchmark_results.md)" -ForegroundColor Gray
}

Write-Host "`n✅ Done!" -ForegroundColor Green
